# Generated by Django 5.1.2 on 2024-10-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0003_alter_product_description_alter_product_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="comments",
            field=models.TextField(blank=True, null=True),
        ),
    ]
