# Generated by Django 5.1.2 on 2024-10-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0005_remove_inventory_minimum_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="channel",
            field=models.CharField(
                choices=[
                    ("online", "Онлайн"),
                    ("in_store", "В магазине"),
                    ("other", "Другое"),
                ],
                default="online",
                max_length=100,
            ),
        ),
    ]
